name: Deploy iOS to Testflight Production
on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:
      release_notes:
        description: "Release Notes"
        required: true
        default: "Production Release"
        type: text
      groups:
        description: "TestFlight Tester Groups"
        required: false
jobs:
  deployIOSTestFlightProduction:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7"
          channel: "stable"
          cache: true
        id: flutter
      - name: Accept Xcode License
        run: sudo xcodebuild -license accept
      - name: Get Packages
        run: flutter pub get
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ios
      - name: Setup app store connect
        run: echo "$APP_STORE_CONNECT_API_KEY" >> ./ios/fastlane/store.json
      - name: Build and Deploy to TestFlight Development
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          cd ./ios
          bundle exec fastlane ios deployTestFlightProduction release_notes:"${{ github.event.inputs.release_notes }}" groups:"${{ github.event.inputs.groups }}"