name: Development Branch Workflow

on:
  push:
    branches:
      - development # This workflow will only run on pushes to the 'development' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run development-specific tests
        run: echo "Running tests for development branch..."
      # Add other steps relevant to your development workflow