name: Deploy iOS to Firebase Development
on:
  workflow_dispatch:
    inputs:
      version:
        description: "App Version"
        required: true
        default: "1.0.0"
      release_notes:
        description: "Release Notes"
        required: true
        default: "Development Release"
        type: text
      groups:
        description: "Firebase Tester Groups"
        required: true
        default: "bid-dev"
      testers:
        description: "Firebase Testers"
        required: false
        default: "rijal@bursainvestasi.co.id"
jobs:
  deployIOSFirebaseDevelopment:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      FIREBASE_SERVICE_ACCOUNT_DEVELOPMENT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEVELOPMENT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7"
          channel: "stable"
          cache: true
        id: flutter
      - name: Accept Xcode License
        run: sudo xcodebuild -license accept
      - name: Get Packages
        run: flutter pub get
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ios
      - name: Set up Firebase authentication
        run: echo "$FIREBASE_SERVICE_ACCOUNT_DEVELOPMENT" >> ./ios/fastlane/service-account-development.json
      - name: Build and Deploy to Firebase App Distribution
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          cd ./ios
          bundle exec fastlane ios deployFirebaseDevelopment version:${{github.event.inputs.version}} build_number:${{github.event.inputs.build_number}} release_notes:${{github.event.inputs.release_notes}} groups:${{github.event.inputs.groups}} testers:${{github.event.inputs.testers}}