name: Deploy Android App to Development

on:
  workflow_dispatch:
    inputs:
      version:
        description: "App Version"
        required: true
        default: "1.0.0"
      build_number:
        description: "Build Number"
        required: true
        default: "1"
      release_notes:
        description: "Release Notes"
        required: true
        default: "Development Build"
      groups:
        description: "Firebase Tester Groups"
        required: true
        default: "Internal"
      testers:
        description: "Firebase Testers"
        required: false
        default: ""
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
Learn more about workflow inputs.
For questions, visit the GitHub Actions community.
To see what's next for Actions, visit our public roadmap.

